name: Generate Sitemap

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Generate Sitemap
      run: |
        python generate_sitemap_md.py  # 调用生成站点地图的 Python 脚本

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add sitemap.md
        git commit -m "Auto-generate sitemap.md"
        git push
