name: Generate Sitemap

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Generate Sitemap
      run: |
        python generate_sitemap_md.py

    - name: Commit and push changes
      run: |
       git config --local user.email "topics.copilot0n@icloud.com"
        git config --local user.name "Carson-We"
        git add sitemap.md
        git commit -m "Auto-generate sitemap.md"
        GIT_TOKEN="${{ secrets.GH_TOKEN }}"
        git push https://$GIT_TOKEN@github.com/Carson-We/Documentation.git
